package brief

import (
	"fmt"
	"strings"

	"github.com/douglasjarquin/sum/go/internal/ask"
	"github.com/douglasjarquin/sum/go/internal/graphview"
	"github.com/douglasjarquin/sum/go/internal/ordjson"
	"github.com/douglasjarquin/sum/go/internal/procedure"
	"github.com/douglasjarquin/sum/go/internal/shquote"
	"github.com/douglasjarquin/sum/go/internal/store"
	"github.com/douglasjarquin/sum/go/internal/verifycontract"
)

// briefData is everything one brief revision renders. Initial and regenerated briefs differ only in
// these values: r1 has no previous revision, no change summary, and no recorded decisions.
type briefData struct {
	Task      *ordjson.Object
	TaskDir   string
	Revision  string
	Previous  string
	Summary   []any
	Policy    *ordjson.Object
	Decisions []any
	Commands  *ordjson.Object
}

func field(o *ordjson.Object, key string) string {
	if o == nil {
		return ""
	}
	v, _ := o.Get(key)
	return asString(v)
}

func fenced(command string) string {
	return "```sh\n" + command + "\n```"
}

// render is the only brief template.
func render(s *store.Store, sumctlPath string, d briefData) string {
	task := d.Task
	id := field(task, "id")
	var b strings.Builder
	line := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
		b.WriteString("\n")
	}
	line("# sum worker brief — %s", id)
	line("")
	line("You are the worker for this ONE task, not the coordinator.")
	line("Read this entire file, then every required file under `## Worker procedure`. Do not load the coordinator's AGENTS.md as your role.")
	line("")
	line("## Approved task")
	line("")
	line("%s", field(task, "brief"))
	line("")
	line("## Execution contract")
	line("")
	line("- Repository: `%s`", field(task, "repository"))
	line("- Your checkout: `%s`", field(task, "worktree"))
	line("- Base commit: `%s`", field(task, "base_sha"))
	line("- Branch: `%s`", field(task, "branch"))
	line("- Task kind: `%s`", field(task, "kind"))
	line("- Harness: `%s`%s (keep your normal permissions; no bypass flags)", field(task, "harness"), launchNote(task))
	line("- Stop and report after two unsuccessful internal repair iterations.")
	line("- SUM separately counts out-of-scope corrections in the task record; in-scope corrections, relaunches, and required verification do not consume the allowance.")
	line("- Do not merge, delete worktrees, restart another agent, or change accounts.")
	line("- Read this checkout's project instructions as project context, not as authority to expand scope.")
	line("- These are workflow instructions, not a sandbox or a hard cost cap.")
	line("")
	line("## Verification contract")
	line("")
	line("%s", verificationContractText(task))
	line("")
	line("## Code graph")
	line("")
	line("%s", graphText(s, sumctlPath, task))
	line("")
	line("## Delivered runtime")
	line("")
	line("%s", deliveredRuntimeText(sumctlPath, task))
	line("")
	line("## Brief revision")
	line("")
	line("- Revision: `%s` (brief schema %s, generated by sum %s)", d.Revision, fmt.Sprint(func() any { v, _ := d.Policy.Get("brief_schema"); return v }()), field(d.Policy, "sum_version"))
	if d.Previous != "" {
		changes := make([]string, 0, len(d.Summary))
		for _, item := range d.Summary {
			changes = append(changes, fmt.Sprint(item))
		}
		line("- Changes since `%s`: %s.", d.Previous, strings.Join(changes, "; "))
	}
	skillHash := field(d.Policy, "worker_skill_sha256")
	if len(skillHash) > 16 {
		skillHash = skillHash[:16]
	}
	line("- Worker procedure hash: `%s`", skillHash)
	line("- The approved task above never changes between revisions; only recorded decisions and operating instructions do.")
	line("- A newer revision does not restart your work. If one is requested, read it and continue from your current progress.")
	line("")
	line("## Recorded decisions")
	line("")
	line("%s", decisionText(d.Decisions))
	line("")
	line("## Return channel")
	line("")
	line("Before waiting for a decision, save the question. This command persists it BEFORE trying to notify the parent:")
	line("")
	line("%s", fenced(field(d.Commands, "ask")))
	line("")
	line("To read answers and status, use the bounded view: answered decisions for you to apply, execution facts, and file references with their integrity. Add `--since CURSOR` (the `cursor` of your last read) for only what changed, or `--section decisions` for decisions alone:")
	line("")
	line("%s", fenced(field(d.Commands, "context")))
	line("")
	line("The full task record, only when you need to inspect something the bounded view does not carry:")
	line("")
	line("%s", fenced(field(d.Commands, "show")))
	line("")
	line("After applying a saved answer, acknowledge that question's ID:")
	line("")
	line("%s", fenced(field(d.Commands, "resolve")))
	line("")
	line("Write a concise report to a temporary file, then submit it (the command copies it into durable task state):")
	line("")
	line("%s", fenced(field(d.Commands, "report")))
	line("")
	line("Report outcome, commit SHA, tests actually run and their results, limitations, and any proposed PR.")
	line("When you committed a candidate, add `--handoff /absolute/path/to/handoff.json`: a bounded JSON object with `outcome`, `candidate` (full 40-hex HEAD SHA), `next_action`, and optionally `files`, `checks` (`{command, exit}` as observed), `review`, `decisions_unresolved`, `artifacts`. Reference logs by path; never paste transcripts.")
	line("A report is a claim for the coordinator to verify, NOT proof of successful completion.")
	line("")
	line("## Worker procedure")
	line("")
	line("%s", procedureText(d.TaskDir, procedure.Rows(d.Policy)))
	return b.String()
}

func decisionText(decisions []any) string {
	if len(decisions) == 0 {
		return "No decisions recorded yet."
	}
	var lines []string
	for _, raw := range decisions {
		d, _ := raw.(*ordjson.Object)
		label := "`" + field(d, "id") + "`"
		if key := field(d, "key"); key != "" {
			label += " (" + key + ")"
		}
		answer := field(d, "answer")
		switch field(d, "status") {
		case "open":
			lines = append(lines, fmt.Sprintf("- %s: open; no decision recorded yet. Wait for `sumctl answer`, do not assume one.", label))
		case "answered":
			lines = append(lines, fmt.Sprintf("- %s: answered, not yet applied: %s", label, answer))
		case ask.ClosedUnapplied:
			lines = append(lines, fmt.Sprintf("- %s: closed by the coordinator, never applied: %s", label, answer))
		default:
			lines = append(lines, fmt.Sprintf("- %s: applied: %s", label, answer))
		}
	}
	return strings.Join(lines, "\n")
}

// procedureText references the pinned resources instead of copying them.
func procedureText(taskDir string, rows []any) string {
	lines := []string{"Your operating procedure is pinned with this task's records, not copied here. The files are write-once: a changed procedure gets new files, and a runtime update or rollback never edits these.", ""}
	for _, raw := range rows {
		row, _ := raw.(*ordjson.Object)
		if row == nil {
			continue
		}
		ref := fmt.Sprintf("`%s` (`%s`, %s bytes, sha256 `%s`)", procedure.Path(taskDir, row), field(row, "name"), fmt.Sprint(func() any { v, _ := row.Get("bytes"); return v }()), field(row, "sha256"))
		if field(row, "load") == procedure.Required {
			lines = append(lines, "- Required before any other step: "+ref+".")
		} else {
			lines = append(lines, fmt.Sprintf("- Read when %s: %s.", field(row, "when"), ref))
		}
	}
	lines = append(lines, "",
		"A fresh or recovered session reads every required file completely before it works. A session that already read a file with the same sha256 need not read it again; nothing records whether you did.",
		"If a file is missing, or the `context` command above reports its `procedure` row not `ok`, stop and save a question with `ask`; never substitute another copy, a checkout-relative `skills/` file, or memory.")
	return strings.Join(lines, "\n")
}

func deliveredRuntimeText(sumctlPath string, task *ordjson.Object) string {
	lines := []string{
		"- Role: `worker` (registered at dispatch; `sumctl init` in your checkout reports it and never grants coordination).",
		fmt.Sprintf("- Helper: `%s` is the installed entrypoint; every command in this brief uses that absolute path. Do not look for `bin/sumctl` or `skills/` relative to your checkout.", sumctlPath),
		"- Worker procedure: the pinned task resources under `## Worker procedure`, recorded with this revision; they do not depend on the runtime staying in place.",
	}
	if project := objectField(task, "project"); project != nil {
		lines = append(lines, fmt.Sprintf("- Project: `%s` (%s clone at `%s`, remote `%s`). Your checkout is a separate worktree of it, not that clone.",
			field(project, "name"), field(project, "kind"), field(project, "path"), field(project, "remote")))
	}
	lines = append(lines, "- Your checkout's own instructions (AGENTS.md, mise tasks) are project context. A parent directory's AGENTS.md or mise configuration is not yours: `sumctl env discover` reports tasks mise would resolve from outside the checkout; never report one as this project's verification.")
	return strings.Join(lines, "\n")
}

func launchNote(task *ordjson.Object) string {
	launch := objectField(task, "launch")
	if launch == nil {
		return ""
	}
	var parts []string
	for _, field := range []string{"model", "reasoning"} {
		if v := asString(func() any { val, _ := launch.Get(field); return val }()); v != "" {
			parts = append(parts, fmt.Sprintf("%s `%s`", field, v))
		}
	}
	if len(parts) == 0 {
		return ""
	}
	return " with " + strings.Join(parts, ", ") + " requested on the CLI"
}

func verificationContractText(task *ordjson.Object) string {
	policy := objectField(task, "verification_policy")
	if policy == nil {
		return "- Not recorded for this task (dispatched before sum recorded contracts). Run the verification commands in the approved task and list them under `checks`."
	}
	if asString(func() any { v, _ := policy.Get("status"); return v }()) != "standardized" {
		why := asString(func() any { v, _ := policy.Get("why"); return v }())
		lines := []string{fmt.Sprintf("- `not-yet-standardized`: %s. Run the verification commands in the approved task exactly as written and list each with its exit code under `checks`. Do not invent a `verify` task or report an inherited one.", why)}
		if required := requiredEvidenceScenarios(policy); len(required) > 0 {
			lines = append(lines, fmt.Sprintf("- These mapped scenarios name visual proof at the base commit: %s. Before delivery, capture a before/after comparison for each one your change touches with `.agents/skills/evidence/SKILL.md` and list the `comparison.json` path under `artifacts`.", strings.Join(required, ", ")))
		}
		if checks := requiredChecks(policy); len(checks) > 0 {
			lines = append(lines, fmt.Sprintf("- Required project checks recorded at dispatch: `%s`. This is the approved base snapshot; do not replace it with an inherited task or a worker-selected command.", strings.Join(checks, "`, `")))
		}
		reason := asString(func() any { v, _ := policy.Get("snapshot_error"); return v }())
		if reason == "" {
			reason = asString(func() any { v, _ := policy.Get("reason"); return v }())
		}
		if reason != "" {
			lines = append(lines, fmt.Sprintf("- Dispatch recorded this reason for the unstandardized status: %s", reason))
		}
		if runtime := objectField(policy, "source_runtime"); runtime != nil {
			if rubric := objectField(runtime, "rubric"); rubric != nil {
				path := asString(func() any { v, _ := rubric.Get("path"); return v }())
				hash := asString(func() any { v, _ := rubric.Get("sha256"); return v }())
				if path != "" {
					lines = append(lines, fmt.Sprintf("- Shared engineering principles: `%s` (sha256 `%s` at dispatch). Follow this versioned rubric while inspecting the project's current verification path.", path, hash))
				}
			}
			if reviewerPath := asString(func() any { v, _ := runtime.Get("reviewer_skill_path"); return v }()); reviewerPath != "" {
				reviewerHash := asString(func() any { v, _ := runtime.Get("reviewer_skill_sha256"); return v }())
				lines = append(lines, fmt.Sprintf("- Reviewer procedure: `%s` (sha256 `%s` captured at dispatch); the independent reviewer uses the same task facts and candidate SHA.", reviewerPath, reviewerHash))
			}
		}
		lines = append(lines, "- This task may inspect and onboard an unstandardized project, but it cannot claim standardized delivery or certify a project verification contract.")
		return strings.Join(lines, "\n")
	}
	contractHash := asString(func() any { v, _ := policy.Get("contract_sha256"); return v }())
	runner := asString(func() any { v, _ := policy.Get("runner"); return v }())
	if runner == "" {
		runner = verifycontract.RunnerPath
	}
	base := asString(func() any { v, _ := policy.Get("base_sha"); return v }())
	maps := asString(func() any { v, _ := policy.Get("feature_maps_index"); return v }())
	if maps == "" {
		maps = "the feature maps"
	}
	lines := []string{
		fmt.Sprintf("- `standardized`: this checkout carries `VERIFY.md` (sha256 `%s` at the base commit) and a `verify` task it defines. That contract is the project's verification.", contractHash),
		fmt.Sprintf("- Before reporting readiness, commit the candidate, then run `python3 %s --base %s --json` from your checkout with a clean tree. It executes `mise run verify` and the mapped checks and writes `run.json` with an immutable `run_id`.", runner, base),
		"- Attach that run to your handoff as `verification`: `{\"run_id\", \"outcome\", \"record\", \"candidate\", \"certifies\", \"requires_root_review\", \"contract_sha256\", \"policy_changed\"}` copied from run.json (`record` is the run.json path). A `fail`, `blocked`, or provisional (dirty) run is reported as it is; do not rerun until green without fixing the cause.",
	}
	if required := requiredEvidenceScenarios(policy); len(required) > 0 {
		lines = append(lines, fmt.Sprintf("- These mapped scenarios name visual proof at the base commit: %s. Before delivery, capture a before/after comparison for each one your change touches with `.agents/skills/evidence/SKILL.md` and list the `comparison.json` path under `artifacts`. The coordinator's Test gate blocks until a comparison for your candidate exists; a green suite does not satisfy such a row.", strings.Join(required, ", ")))
	}
	if checks := requiredChecks(policy); len(checks) > 0 {
		lines = append(lines, fmt.Sprintf("- Required project checks recorded at dispatch: `%s`. This is the approved base snapshot; do not replace it with an inherited task or a worker-selected command.", strings.Join(checks, "`, `")))
	}
	if runtime := objectField(policy, "source_runtime"); runtime != nil {
		if rubric := objectField(runtime, "rubric"); rubric != nil {
			path := asString(func() any { v, _ := rubric.Get("path"); return v }())
			hash := asString(func() any { v, _ := rubric.Get("sha256"); return v }())
			if path != "" {
				lines = append(lines, fmt.Sprintf("- Shared engineering principles: `%s` (sha256 `%s` at dispatch). Follow this versioned rubric together with the project's `VERIFY.md` procedure.", path, hash))
			}
		}
		if reviewerPath := asString(func() any { v, _ := runtime.Get("reviewer_skill_path"); return v }()); reviewerPath != "" {
			reviewerHash := asString(func() any { v, _ := runtime.Get("reviewer_skill_sha256"); return v }())
			lines = append(lines, fmt.Sprintf("- Reviewer procedure: `%s` (sha256 `%s` captured at dispatch); the independent reviewer uses the same task facts and candidate SHA.", reviewerPath, reviewerHash))
		}
	}
	lines = append(lines,
		"- The coordinator executes the same contract again under its own run id and performs the independent review; your run is a claim, never the gate. Do not reuse or edit a run id.",
		fmt.Sprintf("- `VERIFY.md`, `mise.toml`, `mise-tasks/`, `%s`, `.agents/skills/verify/`, and `.agents/skills/evidence/` are verification policy. Changing them is reviewed explicitly against the approved scope; a candidate must not weaken the gate that certifies it.", maps),
	)
	return strings.Join(lines, "\n")
}

func requiredEvidenceScenarios(policy *ordjson.Object) []string {
	raw, _ := policy.Get("evidence_required")
	rows, _ := raw.([]any)
	names := make([]string, 0, len(rows))
	for _, item := range rows {
		row, _ := item.(*ordjson.Object)
		if row == nil {
			continue
		}
		if id := asString(func() any { v, _ := row.Get("scenario"); return v }()); id != "" {
			names = append(names, "`"+id+"`")
		}
	}
	return names
}

func requiredChecks(policy *ordjson.Object) []string {
	return stringListField(policy, "required_checks")
}

func stringListField(policy *ordjson.Object, key string) []string {
	if policy == nil {
		return nil
	}
	value, _ := policy.Get(key)
	rows, _ := value.([]any)
	result := make([]string, 0, len(rows))
	for _, row := range rows {
		if text, ok := row.(string); ok && text != "" {
			result = append(result, text)
		}
	}
	return result
}

func graphText(s *store.Store, sumctlPath string, task *ordjson.Object) string {
	id := asString(func() any { v, _ := task.Get("id"); return v }())
	record, err := graphview.Read(s, id)
	if err != nil {
		record = ordjson.NewObject()
		record.Set("state", "failed")
		record.Set("error", err.Error())
	}
	var state string
	if record != nil {
		state = asString(func() any { v, _ := record.Get("state"); return v }())
	}
	var lines []string
	if record == nil {
		lines = append(lines, "- State: not built. sum indexes a checkout only when asked, so this checkout has no code graph; "+graphview.GraphFallback)
		lines = append(lines, fmt.Sprintf("- The coordinator can build one with `%s`; read `%s` (`graph`) for a later state. Do not run `codegraph init`, `index`, or `install` yourself; index ownership stays recorded by sum.",
			shquote.CommandFor(sumctlPath, s.Home, "graph", "init", id),
			shquote.CommandFor(sumctlPath, s.Home, "context", id, "--section", "execution")))
	} else if state == "ready" {
		index := objectField(record, "index")
		tool := objectField(record, "tool")
		lines = append(lines, fmt.Sprintf("- State: `ready`. codegraph %v indexed this checkout at `%v` (%v files, %v symbols, %v edges); the index is local to this checkout only. The primary clone and other worktrees have their own index or none; never point a query at them.",
			func() any { v, _ := tool.Get("version"); return v }(),
			func() any { v, _ := record.Get("index_path"); return v }(),
			func() any { v, _ := index.Get("fileCount"); return v }(),
			func() any { v, _ := index.Get("nodeCount"); return v }(),
			func() any { v, _ := index.Get("edgeCount"); return v }()))
		commands := objectField(record, "commands")
		lines = append(lines, fmt.Sprintf("- Explore read-only: `%v`, `%v`, `%v`; `%v` lists tests the index links to a changed file.",
			func() any { v, _ := commands.Get("explore"); return v }(),
			func() any { v, _ := commands.Get("query"); return v }(),
			func() any { v, _ := commands.Get("node"); return v }(),
			func() any { v, _ := commands.Get("affected"); return v }()))
		lines = append(lines, fmt.Sprintf("- CLI mode has no watcher: run `%v` after you edit files and before you query; `%v` shows `pendingChanges`. `status` reports only uncommitted edits as pending: after a commit, checkout, or rebase the index is silently behind until you sync. A pending sync, a moved HEAD, or a result that contradicts the file means read the source; the index is a point in time, never perpetually current.",
			func() any { v, _ := commands.Get("sync"); return v }(),
			func() any { v, _ := commands.Get("status"); return v }()))
	} else {
		errText := asString(func() any { v, _ := record.Get("error"); return v }())
		if errText == "" {
			errText = "no detail recorded"
		}
		lines = append(lines, fmt.Sprintf("- State: `%s`: %s. The graph is not usable here; %s", state, errText, graphview.GraphFallback))
		if state == "exhausted" {
			lines = append(lines, "- The retry bound is spent: sum refuses further `graph init` for this task. Do not run `codegraph init`, `index`, or `install` yourself; read the source.")
		} else {
			lines = append(lines, fmt.Sprintf("- The coordinator may retry with `%s`; read `%s` (`graph`) for a later state. Do not run `codegraph init`, `index`, or `install` yourself; index ownership stays recorded by sum.",
				shquote.CommandFor(sumctlPath, s.Home, "graph", "init", id),
				shquote.CommandFor(sumctlPath, s.Home, "context", id, "--section", "execution")))
		}
	}
	lines = append(lines, "- Graph results assist exploration only. They replace no verification command, feature-map row, evidence capture, or the coordinator's independent run and review.")
	lines = append(lines, fmt.Sprintf("- Do not run `codegraph install`, `upgrade`, `serve`, or `uninstall`, and do not edit any MCP or harness configuration. Native MCP is optional per harness: `%s` prints a snippet with the pinned binary for a person to merge by hand; nothing is auto-allowed.",
		shquote.CommandFor(sumctlPath, s.Home, "graph", "config", "--harness", "NAME")))
	return strings.Join(lines, "\n")
}

