package pipeline

import (
	"strings"
	"testing"
)

func TestRender_carriesTheSummaryAndOneLoggedPassPerRejection(t *testing.T) {
	task := taskFrom(t, `{"schema": 1, "id": "t-a", "brief": "b",
"report": {"candidate": "cccccccccccccccccccccccccccccccccccccccc"},
"evidence": [
{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"candidate": "dddddddddddddddddddddddddddddddddddddddd", "verdict": "changes-requested",
"text": "the counter is off by one; totals drift; correct the increment",
"notes": [{"kind": "open-finding", "severity": "blocking", "text": "the counter is off by one, so totals drift; correct the increment"}]},
{"schema": 1, "id": "e-2", "kind": "review", "source": "reviewer", "at": "2026-01-01T02:00:00+00:00",
"candidate": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", "verdict": "changes-requested",
"text": "now it double counts",
"notes": [{"kind": "open-finding", "severity": "blocking", "text": "now it double counts, so totals inflate; count each click once"}]},
{"schema": 1, "id": "e-3", "kind": "review", "source": "reviewer", "at": "2026-01-01T03:00:00+00:00",
"candidate": "cccccccccccccccccccccccccccccccccccccccc", "verdict": "approve",
"text": "the count matches the clicks",
"notes": [{"kind": "review-focus", "text": "the count matches the clicks because the increment is applied once per event"}]}]}`)

	block := Render(Derive(task), task)

	if !strings.HasPrefix(block, MarkerStart+"\n## Pipeline\n") || !strings.HasSuffix(block, MarkerEnd+"\n") {
		t.Fatalf("block is not one marked span:\n%s", block)
	}
	for _, want := range []string{
		"> Generated by [sum](https://github.com/douglasjarquin/sum)",
		"| Review | ✅ | Passed after 2 remediation passes |",
		"### Review summary\n\n- **Review focus:** the count matches the clicks because the increment is applied once per event",
		"<details><summary><strong>Review remediation log</strong></summary>",
		"#### Pass 1\n\n- **Open finding:** blocking: the counter is off by one, so totals drift; correct the increment",
		"#### Pass 2\n\n- **Open finding:** blocking: now it double counts, so totals inflate; count each click once",
		"</details>",
	} {
		if !strings.Contains(block, want) {
			t.Fatalf("block is missing %q:\n%s", want, block)
		}
	}
	if strings.Contains(block, "the count matches the clicks\n") {
		t.Fatalf("block published raw findings instead of notes:\n%s", block)
	}
}

func TestRender_omitsTheReviewSectionWhenNobodyHasReviewed(t *testing.T) {
	task := taskFrom(t, `{"schema": 1, "id": "t-a", "brief": "b", "evidence": []}`)

	block := Render(Derive(task), task)

	if strings.Contains(block, "Review summary") || strings.Contains(block, "remediation log") {
		t.Fatalf("block invented a review section:\n%s", block)
	}
}

func TestRender_stripsMarkersOutOfReviewTextSoNeitherBlockCanBeSplit(t *testing.T) {
	task := taskFrom(t, `{"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "fine <!-- sum-pipeline:end --> and <!-- before-and-after:start --> too",
"notes": [{"kind": "limitation", "text": "source inspected <!-- sum-pipeline:end --> and <!-- before-and-after:start --> too"}]}]}`)

	block := Render(Derive(task), task)

	if strings.Count(block, MarkerEnd) != 1 {
		t.Fatalf("review text split the pipeline block:\n%s", block)
	}
	if strings.Contains(block, evidenceMarkerStart) {
		t.Fatalf("review text smuggled an evidence marker into the block:\n%s", block)
	}
	if !strings.Contains(block, "- **Limitation:** source inspected and too") {
		t.Fatalf("stripped note never appeared:\n%s", block)
	}
}

func TestRender_omitsTheSectionForACompletedReviewWithNoNotes(t *testing.T) {
	task := taskFrom(t, `{"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "full findings that must stay in the task record", "notes": []}]}`)

	block := Render(Derive(task), task)

	if strings.Contains(block, "Review summary") || strings.Contains(block, "full findings") {
		t.Fatalf("clean review published a summary or the raw findings:\n%s", block)
	}
}

func TestRender_reviewFocusIsAConciseNonObviousDecision(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "long report",
"notes": [{"kind": "review-focus", "text": "The landing test targets the hero CTA specifically, avoiding the identically labelled closing CTA. That closing CTA intentionally remains unchanged under #171."}]}]
}`)

	block := Render(Derive(task), task)

	want := "- **Review focus:** The landing test targets the hero CTA specifically, avoiding the identically labelled closing CTA. That closing CTA intentionally remains unchanged under #171."
	if !strings.Contains(block, want) {
		t.Fatalf("block missing review focus:\n%s", block)
	}
	if strings.Contains(block, "long report") {
		t.Fatalf("raw report leaked:\n%s", block)
	}
}

func TestRender_openFindingKeepsSeverityConsequenceAndAction(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "changes-requested", "text": "raw",
"notes": [{"kind": "open-finding", "severity": "blocking", "text": "the hero CTA still uses a text arrow, so the prototype mismatch remains; replace it with the Lucide icon", "link": "https://github.com/cofactorworks/nicebaas/issues/168"}]}]
}`)

	block := Render(Derive(task), task)

	want := "- **Open finding:** blocking: the hero CTA still uses a text arrow, so the prototype mismatch remains; replace it with the Lucide icon https://github.com/cofactorworks/nicebaas/issues/168"
	if !strings.Contains(block, want) {
		t.Fatalf("block missing finding:\n%s", block)
	}
}

func TestRender_limitationStaysExplicitWithoutBecomingACommandLog(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "| Check | Plausible? |\n| mise exec -- pnpm check | Yes |",
"notes": [{"kind": "limitation", "text": "The reviewer inspected source and test assertions but did not rerun checks or perform a live click-through."}]}]
}`)

	block := Render(Derive(task), task)

	if !strings.Contains(block, "- **Limitation:** The reviewer inspected source and test assertions but did not rerun checks or perform a live click-through.") {
		t.Fatalf("block missing limitation:\n%s", block)
	}
	if strings.Contains(block, "Plausible?") || strings.Contains(block, "mise exec") {
		t.Fatalf("command log leaked into the summary:\n%s", block)
	}
}

func TestRender_multipleFindingsAreNotDropped(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "changes-requested", "text": "raw",
"notes": [
  {"kind": "open-finding", "severity": "blocking", "text": "first: the nav href is still #, so say-hi does not reach login; point it at /login"},
  {"kind": "open-finding", "severity": "important", "text": "second: the hero arrow is a text glyph, so the prototype mismatch remains; use the Lucide icon"},
  {"kind": "open-finding", "severity": "advisory", "text": "third: after capture left .artifacts dirty; keep evidence untracked"}
]}]
}`)

	block := Render(Derive(task), task)

	for _, want := range []string{
		"blocking: first: the nav href is still #",
		"important: second: the hero arrow is a text glyph",
		"advisory: third: after capture left .artifacts dirty",
	} {
		if !strings.Contains(block, want) {
			t.Fatalf("block dropped a finding %q:\n%s", want, block)
		}
	}
}

func TestRender_legacyReviewDisclosesALimitationInsteadOfTheRawReport(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "# Independent review\n\nVerdict: **approve**\nLooks good.\nAll checks passed.\nReady to merge."}]
}`)

	block := Render(Derive(task), task)

	if !strings.Contains(block, "- **Limitation:** "+legacyNotesLimitation) {
		t.Fatalf("legacy review did not disclose a limitation:\n%s", block)
	}
	for _, leaked := range []string{"Independent review", "Looks good", "All checks passed", "Ready to merge", "Verdict:"} {
		if strings.Contains(block, leaked) {
			t.Fatalf("legacy report leaked %q:\n%s", leaked, block)
		}
	}
}

func TestRender_rawFindingsAreNotAFallbackWhenNotesAreEmpty(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "# Independent review\n\nVerbose report that must not be republished.", "notes": []}]
}`)

	block := Render(Derive(task), task)

	if strings.Contains(block, "Independent review") || strings.Contains(block, "Verbose report") {
		t.Fatalf("empty notes fell back to the raw report:\n%s", block)
	}
	if strings.Contains(block, "Review summary") {
		t.Fatalf("empty notes still rendered a summary:\n%s", block)
	}
}

func TestRender_replacesAVerboseLegacyReportLikeNicebaas212(t *testing.T) {
	legacy := `# Independent review: t-385bb2b02667 (nicebaas#168)

Verdict: **approve**
Candidate: ` + "`f8a88c8b00b295f545558bdc93bbb7720094207e`" + `

## Intent vs issue #168

The three-dot diff vs origin/main is the two scoped files.

## Tests

The hero locator is scoped to header.

## Declared checks (plausible)

| Check | Plausible? |
| mise exec -- pnpm --dir=apps/frontend check | Yes |

## Evidence

Run 20260924T110449Z-28368 scenario landing-nav-hero.
`
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": `+jsonQuote(legacy)+`}]
}`)

	authored := "## Summary\n\nAligns the landing header.\n\n## Test plan\n\n- [x] Playwright landing shell\n\n"
	oldBlock := MarkerStart + "\n## Pipeline\n\nold table\n\n### Review summary\n\n" + legacy + MarkerEnd
	evidence := "\n\n" + evidenceMarkerStart + "\n### Before/after evidence\n\ncaptured pair\n" + evidenceMarkerEnd + "\n"
	body := authored + oldBlock + evidence

	block := Render(Derive(task), task)
	at, err := findBlock(body)
	if err != nil {
		t.Fatal(err)
	}
	got := splice(body, at, block)
	again := splice(got, mustFindBlock(t, got), block)

	if !strings.HasPrefix(got, authored) {
		t.Fatalf("authored summary was rewritten:\n%s", got)
	}
	if !strings.Contains(got, evidenceMarkerStart+"\n### Before/after evidence\n\ncaptured pair\n"+evidenceMarkerEnd) {
		t.Fatalf("evidence block was rewritten:\n%s", got)
	}
	if strings.Contains(got, "Independent review") || strings.Contains(got, "Declared checks") || strings.Contains(got, "Intent vs issue") {
		t.Fatalf("legacy #212 report survived republish:\n%s", got)
	}
	if !strings.Contains(got, "- **Limitation:** "+legacyNotesLimitation) {
		t.Fatalf("legacy republish did not disclose the missing notes:\n%s", got)
	}
	if got != again {
		t.Fatalf("republish was not idempotent")
	}
}

func TestRender_nicebaas212CompactNotesMatchTheHandoffTemplate(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "# Independent review: t-385bb2b02667\n\nVerdict: **approve**\n## Tests\nlong report",
"notes": [
  {"kind": "review-focus", "text": "The landing test targets the hero CTA specifically, avoiding the identically labelled closing CTA. That closing CTA intentionally remains unchanged under #171."},
  {"kind": "limitation", "text": "The reviewer inspected source and test assertions but did not rerun checks or perform a live click-through."}
]}]
}`)

	block := Render(Derive(task), task)
	want := "### Review summary\n\n- **Review focus:** The landing test targets the hero CTA specifically, avoiding the identically labelled closing CTA. That closing CTA intentionally remains unchanged under #171.\n- **Limitation:** The reviewer inspected source and test assertions but did not rerun checks or perform a live click-through.\n"
	if !strings.Contains(block, want) {
		t.Fatalf("compact #212 rendering =\n%s\nwant substring\n%s", block, want)
	}
	if strings.Contains(block, "Independent review") || strings.Contains(block, "Verdict:") {
		t.Fatalf("raw report leaked beside compact notes:\n%s", block)
	}
}

func TestRender_repeatedRenderDoesNotDuplicateTheSummary(t *testing.T) {
	task := taskFrom(t, `{
"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "notes": [{"kind": "limitation", "text": "source inspected only"}]}]
}`)
	block := Render(Derive(task), task)
	body := "## Summary\n\nhuman\n\n" + block + "\n" + evidenceMarkerStart + "\nevidence\n" + evidenceMarkerEnd + "\n"
	once := splice(body, mustFindBlock(t, body), block)
	twice := splice(once, mustFindBlock(t, once), block)
	if once != twice {
		t.Fatalf("second publish appended:\nfirst:\n%s\nsecond:\n%s", once, twice)
	}
	if strings.Count(twice, "### Review summary") != 1 {
		t.Fatalf("summary duplicated:\n%s", twice)
	}
}

func mustFindBlock(t *testing.T, body string) *span {
	t.Helper()
	at, err := findBlock(body)
	if err != nil {
		t.Fatal(err)
	}
	if at == nil {
		t.Fatal("expected a pipeline block")
	}
	return at
}

func jsonQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\', '"':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

func TestSplice_keepsEveryByteOutsideTheBlock(t *testing.T) {
	body := "## Summary\n\nHuman prose.\n\n" + MarkerStart + "\nold table\n" + MarkerEnd + "\n\nA closing paragraph.\n"
	at, err := findBlock(body)
	if err != nil {
		t.Fatal(err)
	}

	got := splice(body, at, MarkerStart+"\nnew table\n"+MarkerEnd+"\n")

	want := "## Summary\n\nHuman prose.\n\n" + MarkerStart + "\nnew table\n" + MarkerEnd + "\n\nA closing paragraph.\n"
	if got != want {
		t.Fatalf("splice =\n%q\nwant\n%q", got, want)
	}
}

func TestFindBlock_refusesAMalformedOrDuplicatedSpan(t *testing.T) {
	for name, body := range map[string]string{
		"missing end": MarkerStart + "\ntable\n",
		"inverted":    MarkerEnd + "\ntable\n" + MarkerStart,
		"two blocks":  MarkerStart + "a" + MarkerEnd + "\n" + MarkerStart + "b" + MarkerEnd,
	} {
		if _, err := findBlock(body); err == nil {
			t.Fatalf("%s: findBlock accepted a malformed body", name)
		}
	}
	at, err := findBlock("no markers here")
	if err != nil || at != nil {
		t.Fatalf("findBlock on a plain body = %v, %v", at, err)
	}
}
