package pipeline

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/douglasjarquin/sum/go/internal/ordjson"
)

const (
	MarkerStart = "<!-- sum-pipeline:start -->"
	MarkerEnd   = "<!-- sum-pipeline:end -->"

	evidenceMarkerStart = "<!-- before-and-after:start -->"
	evidenceMarkerEnd   = "<!-- before-and-after:end -->"

	attribution = "> Generated by [sum](https://github.com/douglasjarquin/sum)"
)

type span struct {
	start int
	end   int
}

// findBlock returns the one marked span, or nil. Two starts, a missing end, or an inverted pair is malformed and refused.
func findBlock(body string) (*span, error) {
	start, end := strings.Index(body, MarkerStart), strings.Index(body, MarkerEnd)
	if start == -1 && end == -1 {
		return nil, nil
	}
	if start == -1 || end == -1 || end < start {
		return nil, fmt.Errorf("the PR body has an incomplete sum-pipeline marker block; fix it by hand before publishing")
	}
	if strings.Index(body[start+len(MarkerStart):], MarkerStart) != -1 || strings.Index(body[end+len(MarkerEnd):], MarkerEnd) != -1 {
		return nil, fmt.Errorf("the PR body has more than one sum-pipeline marker block; publication owns exactly one")
	}
	return &span{start: start, end: end + len(MarkerEnd)}, nil
}

// splice replaces only the marked span, or appends. Every other byte of the body is kept.
func splice(body string, at *span, block string) string {
	if at == nil {
		prefix := strings.TrimRight(body, " \t\r\n")
		if prefix == "" {
			return block
		}
		return prefix + "\n\n" + block
	}
	return body[:at.start] + strings.TrimRight(block, "\n") + body[at.end:]
}

func normalize(text string) string {
	text = strings.ReplaceAll(text, "\r\n", "\n")
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		lines[i] = strings.TrimRight(line, " \t")
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}

func blockHash(text string) string {
	sum := sha256.Sum256([]byte(normalize(text)))
	return hex.EncodeToString(sum[:])
}

const (
	noteFocus   = "review-focus"
	noteFinding = "open-finding"
	noteLimit   = "limitation"

	legacyNotesLimitation = "The recorded review has no structured notes. Full findings stay in the task record and were not published here."
	emptyPassLimitation   = "This pass recorded no structured notes."
)

var noteOrder = []string{noteFocus, noteFinding, noteLimit}

var noteLabels = map[string]string{
	noteFocus:   "Review focus",
	noteFinding: "Open finding",
	noteLimit:   "Limitation",
}

type reviewNote struct {
	kind     string
	text     string
	severity string
	link     string
}

// Render is the block sum owns in the PR body: the stage table, then a compact review summary of structured notes.
func Render(record Record, task *ordjson.Object) string {
	var out strings.Builder
	out.WriteString(MarkerStart + "\n## Pipeline\n\n" + attribution + "\n\n")
	out.WriteString(record.Table())
	if review := renderReview(task); review != "" {
		out.WriteString("\n" + review)
	}
	out.WriteString(MarkerEnd + "\n")
	return out.String()
}

// renderReview reads every review the task ever collected, not only this candidate's: the remediation log
// is the history of the candidates that were sent back, which by definition are not the current one.
// Publication uses structured notes only. The durable findings text is never copied into the PR.
func renderReview(task *ordjson.Object) string {
	reviews := reviewHistory(task)
	if len(reviews) == 0 {
		return ""
	}
	var summary string
	var haveSummary bool
	var remediation []string
	for _, record := range reviews {
		body := compactReviewBody(record)
		switch stringField(record, "verdict") {
		case "changes-requested":
			if body != "" {
				remediation = append(remediation, body)
			}
		case "approve", "blocked":
			summary = body
			haveSummary = true
		}
	}
	if !haveSummary && len(remediation) > 0 {
		summary = remediation[len(remediation)-1]
		haveSummary = true
	}
	if !haveSummary || (summary == "" && len(remediation) == 0) {
		return ""
	}
	var out strings.Builder
	out.WriteString("### Review summary\n")
	if summary != "" {
		out.WriteString("\n" + summary + "\n")
	} else {
		out.WriteString("\n")
	}
	if len(remediation) > 0 {
		out.WriteString("\n<details><summary><strong>Review remediation log</strong></summary>\n\n")
		for i, text := range remediation {
			out.WriteString(fmt.Sprintf("#### Pass %d\n\n%s\n\n", i+1, text))
		}
		out.WriteString("</details>\n")
	}
	return out.String()
}

func reviewHistory(task *ordjson.Object) []*ordjson.Object {
	var out []*ordjson.Object
	for _, record := range records(task) {
		if stringField(record, "kind") == "review" {
			out = append(out, record)
		}
	}
	return out
}

func compactReviewBody(record *ordjson.Object) string {
	notes, known := notesFromRecord(record)
	if !known {
		return renderNoteBullets([]reviewNote{{kind: noteLimit, text: legacyNotesLimitation}})
	}
	if len(notes) == 0 {
		if stringField(record, "verdict") == "changes-requested" {
			return renderNoteBullets([]reviewNote{{kind: noteLimit, text: emptyPassLimitation}})
		}
		return ""
	}
	return renderNoteBullets(notes)
}

func notesFromRecord(record *ordjson.Object) ([]reviewNote, bool) {
	if record == nil {
		return nil, false
	}
	raw, has := record.Get("notes")
	if !has || raw == nil {
		return nil, false
	}
	items, ok := raw.([]any)
	if !ok {
		return nil, false
	}
	var notes []reviewNote
	for _, item := range items {
		row, _ := item.(*ordjson.Object)
		if row == nil {
			continue
		}
		kind := stripMarkers(stringField(row, "kind"))
		if noteLabels[kind] == "" {
			continue
		}
		text := collapseNoteText(stripMarkers(stringField(row, "text")))
		if text == "" {
			continue
		}
		notes = append(notes, reviewNote{
			kind:     kind,
			text:     text,
			severity: collapseNoteText(stripMarkers(stringField(row, "severity"))),
			link:     collapseNoteText(stripMarkers(stringField(row, "link"))),
		})
	}
	return notes, true
}

func renderNoteBullets(notes []reviewNote) string {
	grouped := map[string][]reviewNote{}
	for _, note := range notes {
		grouped[note.kind] = append(grouped[note.kind], note)
	}
	var lines []string
	for _, kind := range noteOrder {
		for _, note := range grouped[kind] {
			lines = append(lines, "- **"+noteLabels[kind]+":** "+formatNoteText(note))
		}
	}
	return strings.Join(lines, "\n")
}

func formatNoteText(note reviewNote) string {
	text := note.text
	if note.kind == noteFinding && note.severity != "" {
		prefix := note.severity + ": "
		if !strings.HasPrefix(strings.ToLower(text), strings.ToLower(prefix)) {
			text = prefix + text
		}
	}
	if note.link != "" && !strings.Contains(text, note.link) {
		text = strings.TrimSpace(text + " " + note.link)
	}
	return text
}

func collapseNoteText(text string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(text, "\n", " ")), " ")
}

// stripMarkers removes both marker families, so a reviewer's quoted marker can never split either block.
func stripMarkers(text string) string {
	for _, marker := range []string{MarkerStart, MarkerEnd, evidenceMarkerStart, evidenceMarkerEnd} {
		text = strings.ReplaceAll(text, marker, "")
	}
	return strings.TrimSpace(text)
}
