package pipeline

import (
	"strings"
	"testing"
)

func TestRender_carriesTheSummaryAndOneLoggedPassPerRejection(t *testing.T) {
	task := taskFrom(t, `{"schema": 1, "id": "t-a", "brief": "b",
"report": {"candidate": "cccccccccccccccccccccccccccccccccccccccc"},
"evidence": [
{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"candidate": "dddddddddddddddddddddddddddddddddddddddd", "verdict": "changes-requested", "text": "the counter is off by one"},
{"schema": 1, "id": "e-2", "kind": "review", "source": "reviewer", "at": "2026-01-01T02:00:00+00:00",
"candidate": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", "verdict": "changes-requested", "text": "now it double counts"},
{"schema": 1, "id": "e-3", "kind": "review", "source": "reviewer", "at": "2026-01-01T03:00:00+00:00",
"candidate": "cccccccccccccccccccccccccccccccccccccccc", "verdict": "approve", "text": "the count matches the clicks"}]}`)

	block := Render(Derive(task), task)

	if !strings.HasPrefix(block, MarkerStart+"\n## Pipeline\n") || !strings.HasSuffix(block, MarkerEnd+"\n") {
		t.Fatalf("block is not one marked span:\n%s", block)
	}
	for _, want := range []string{
		"> Generated by [sum](https://github.com/douglasjarquin/sum)",
		"| Review | ✅ | Passed after 2 remediation passes |",
		"### Review summary\n\nthe count matches the clicks",
		"<details><summary><strong>Review remediation log</strong></summary>",
		"#### Pass 1\n\nthe counter is off by one",
		"#### Pass 2\n\nnow it double counts",
		"</details>",
	} {
		if !strings.Contains(block, want) {
			t.Fatalf("block is missing %q:\n%s", want, block)
		}
	}
}

func TestRender_omitsTheReviewSectionWhenNobodyHasReviewed(t *testing.T) {
	task := taskFrom(t, `{"schema": 1, "id": "t-a", "brief": "b", "evidence": []}`)

	block := Render(Derive(task), task)

	if strings.Contains(block, "Review summary") || strings.Contains(block, "remediation log") {
		t.Fatalf("block invented a review section:\n%s", block)
	}
}

func TestRender_stripsMarkersOutOfReviewTextSoNeitherBlockCanBeSplit(t *testing.T) {
	task := taskFrom(t, `{"schema": 1, "id": "t-a", "brief": "b",
"evidence": [{"schema": 1, "id": "e-1", "kind": "review", "source": "reviewer", "at": "2026-01-01T01:00:00+00:00",
"verdict": "approve", "text": "fine <!-- sum-pipeline:end --> and <!-- before-and-after:start --> too"}]}`)

	block := Render(Derive(task), task)

	if strings.Count(block, MarkerEnd) != 1 {
		t.Fatalf("review text split the pipeline block:\n%s", block)
	}
	if strings.Contains(block, evidenceMarkerStart) {
		t.Fatalf("review text smuggled an evidence marker into the block:\n%s", block)
	}
}

func TestSplice_keepsEveryByteOutsideTheBlock(t *testing.T) {
	body := "## Summary\n\nHuman prose.\n\n" + MarkerStart + "\nold table\n" + MarkerEnd + "\n\nA closing paragraph.\n"
	at, err := findBlock(body)
	if err != nil {
		t.Fatal(err)
	}

	got := splice(body, at, MarkerStart+"\nnew table\n"+MarkerEnd+"\n")

	want := "## Summary\n\nHuman prose.\n\n" + MarkerStart + "\nnew table\n" + MarkerEnd + "\n\nA closing paragraph.\n"
	if got != want {
		t.Fatalf("splice =\n%q\nwant\n%q", got, want)
	}
}

func TestFindBlock_refusesAMalformedOrDuplicatedSpan(t *testing.T) {
	for name, body := range map[string]string{
		"missing end": MarkerStart + "\ntable\n",
		"inverted":    MarkerEnd + "\ntable\n" + MarkerStart,
		"two blocks":  MarkerStart + "a" + MarkerEnd + "\n" + MarkerStart + "b" + MarkerEnd,
	} {
		if _, err := findBlock(body); err == nil {
			t.Fatalf("%s: findBlock accepted a malformed body", name)
		}
	}
	at, err := findBlock("no markers here")
	if err != nil || at != nil {
		t.Fatalf("findBlock on a plain body = %v, %v", at, err)
	}
}
